### ISSUE TITLE
Error message if user doesn't select gender or type

### ISSUE THREAD

**Issue by wanwisac** [tsongpon/majoingun#9]
<img width="1280" alt="screen shot 2559-01-03 at 9 41 07 pm" src="https://cloud.githubusercontent.com/assets/6838541/12079196/e769adb4-b262-11e5-8c25-009f547ab05a.png">

This error show when i didn't select radio button (gender or type). it should be change to sentence.

**Comment by tsongpon** [comment]
Fixed
